#!/usr/bin/env bash

# Install dependencies
sudo apt install python3 python3-pip git unzip
# Create a new virtual env
python3 -m venv tasmota
# Activate, upgrade pip and install platformio
. tasmota/bin/activate
pip install --upgrade pip
pip install -U platformio
pip install esptool
# Download sources
#git clone https://github.com/arendst/Sonoff-Tasmota.git
# Sources have been downloaded and are attached for stability
unzip Sonoff-Tasmota.zip
mv Sonoff-Tasmota-development src-tasmota
# Create user config file
#cp src-tasmota/sonoff/user_config_override_sample.h src-tasmota/sonoff/user_config_override.h
# User config file is generated by python script
mkdir bin